services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    env_file: ["../.env"]
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file: ["../.env"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: